# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    # Prevent dependabot from opening PRs
    open-pull-requests-limit: 0      
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    # Prevent dependabot from opening PRs
    open-pull-requests-limit: 0      
    allow:
      - dependency-type: "production"
